# docker-compose.yml

services:
  db:
    image: mysql:latest
    container_name: "db_cont"
    env_file:
      - .env
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
      - MYSQL_DATABASE=formula
    volumes:
      - mysql_volume:/var/lib/mysql

  bot_app:
    image: bot_app
    build:
      dockerfile: Dockerfile
    container_name: bot_cont
    restart: always
    env_file:
      - .env
    depends_on:
      - db

volumes:
  mysql_volume:
